services:
  db:
    image: postgres:15
    container_name: postgres_credito
    environment:
      POSTGRES_DB: credito_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_credito
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/credito_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  frontend:
    build:
      context: ../frontend/frontend-credito
    container_name: frontend_credito
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
